### ISSUE TITLE
Custom Scrollbar does not work on iPhone

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-scrollbar-changelog#1]
This issue can be replicated by viewing the [CodyHouse demo page](https://codyhouse.co/ds/components/app/scrollbar) on an iPhone XS using safari
![Screen-Recording-2020-05-07-at-9](https://user-images.githubusercontent.com/16456162/81303929-fbccd300-9041-11ea-8fcf-940bae0f689c.gif)

**Comment by sebastiano-guerriero** [comment]
Hi Emily,

I just tested on Safari (Mac and iOS), and it appears to be working fine. Are you testing using a simulator (e.g., using the developer tools on Safari), or an actual iOS device? Simulators may not be 100% reliable.
